[colors]
[colors.primary]
background = '#090300'
foreground = '#ff3c3c'

[colors.normal]
black   = "#090300"
red     = "#ff1100"
green   = "#01a252"
yellow  = "#ff3c3c"
blue    = "#26bdfd"
magenta = "#a16a94"
cyan    = "#b5e4f4"
white   = "#a5a2a2"

[colors.bright]
black   = "#5c5855"
red     = "#e8bbd0"
green   = "#3a3432"
yellow  = "#ff9494"
blue    = "#807d7c"
magenta = "#d6d5d4"
cyan    = "#cdab53"
white   = "#f7f7f7"

[colors.cursor]
text   = "#090300"
cursor = "#ff3c3c"
