file_panel_border = '#5c5855'
sidebar_border = '#5c5855'
footer_border = '#5c5855'

file_panel_border_active = '#26bdfd'
sidebar_border_active = '#26bdfd'
footer_border_active = '#26bdfd'
modal_border_active = '#26bdfd'

full_screen_bg = '#090300'
file_panel_bg = '#090300'
sidebar_bg = '#090300'
footer_bg = '#090300'
modal_bg = '#090300'

full_screen_fg = '#ff3c3c'
file_panel_fg = '#ff3c3c'
sidebar_fg = '#ff3c3c'
footer_fg = '#ff3c3c'
modal_fg = '#ff3c3c'

cursor = '#ff3c3c'
correct = '#01a252'
error = '#ff1100'
hint = '#26bdfd'
cancel = '#ff1100'
gradient_color = ['#090300', "#5c5855"]

file_panel_top_directory_icon = '#fded02'
file_panel_top_path = '#a5a2a2'
file_panel_item_selected_fg = '#fded02'
file_panel_item_selected_bg = '#1a1412'

sidebar_title = '#26bdfd'
sidebar_item_selected_fg = '#fded02'
sidebar_item_selected_bg = '#1a1412'
sidebar_divider = '#5c5855'

modal_cancel_fg = "#090300"
modal_cancel_bg = '#ff1100'
modal_confirm_fg = "#090300"
modal_confirm_bg = '#01a252'
